# coding: utf-8

"""
    Wodby 2.0 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.stacks_api import StacksApi


class TestStacksApi(unittest.TestCase):
    """StacksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StacksApi()

    def tearDown(self) -> None:
        pass

    def test_stack_revisions_id_get(self) -> None:
        """Test case for stack_revisions_id_get

        Get stack revision
        """
        pass

    def test_stack_revisions_id_services_get(self) -> None:
        """Test case for stack_revisions_id_services_get

        List stack services
        """
        pass

    def test_stacks_by_name_name_get(self) -> None:
        """Test case for stacks_by_name_name_get

        Get stack by name
        """
        pass

    def test_stacks_get(self) -> None:
        """Test case for stacks_get

        List stacks
        """
        pass


if __name__ == '__main__':
    unittest.main()
