# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.update_app_auth_input import UpdateAppAuthInput

class TestUpdateAppAuthInput(unittest.TestCase):
    """UpdateAppAuthInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAppAuthInput:
        """Test UpdateAppAuthInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAppAuthInput`
        """
        model = UpdateAppAuthInput()
        if include_optional:
            return UpdateAppAuthInput(
                app_service_id = 56,
                app_route_id = 56,
                login = '',
                password = '',
                realm = ''
            )
        else:
            return UpdateAppAuthInput(
                login = '',
                realm = '',
        )
        """

    def testUpdateAppAuthInput(self):
        """Test UpdateAppAuthInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
