# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.app_access_cleanup import AppAccessCleanup

class TestAppAccessCleanup(unittest.TestCase):
    """AppAccessCleanup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAccessCleanup:
        """Test AppAccessCleanup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAccessCleanup`
        """
        model = AppAccessCleanup()
        if include_optional:
            return AppAccessCleanup(
                id = 56,
                app_access_id = 56,
                app_instance_id = 56,
                integration_id = 56,
                provider = '',
                status = '',
                attempts = 56,
                last_error = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AppAccessCleanup(
                id = 56,
                app_access_id = 56,
                app_instance_id = 56,
                integration_id = 56,
                provider = '',
                status = '',
                attempts = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAppAccessCleanup(self):
        """Test AppAccessCleanup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
