# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.search_integrations_input import SearchIntegrationsInput

class TestSearchIntegrationsInput(unittest.TestCase):
    """SearchIntegrationsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchIntegrationsInput:
        """Test SearchIntegrationsInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchIntegrationsInput`
        """
        model = SearchIntegrationsInput()
        if include_optional:
            return SearchIntegrationsInput(
                org_id = 56,
                project_ids = [
                    56
                    ],
                types = [
                    'GIT'
                    ],
                statuses = [
                    'OK'
                    ],
                labels = [
                    ''
                    ],
                variables = [
                    wodby.models.integration_variable_requirement_input.IntegrationVariableRequirementInput(
                        name = '0', 
                        secret = True, 
                        optional = True, )
                    ],
                env_id = 1
            )
        else:
            return SearchIntegrationsInput(
        )
        """

    def testSearchIntegrationsInput(self):
        """Test SearchIntegrationsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
