# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.new_database_db_input import NewDatabaseDBInput

class TestNewDatabaseDBInput(unittest.TestCase):
    """NewDatabaseDBInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewDatabaseDBInput:
        """Test NewDatabaseDBInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewDatabaseDBInput`
        """
        model = NewDatabaseDBInput()
        if include_optional:
            return NewDatabaseDBInput(
                database_id = 56,
                name = '',
                charset = '',
                collation = ''
            )
        else:
            return NewDatabaseDBInput(
                database_id = 56,
                name = '',
        )
        """

    def testNewDatabaseDBInput(self):
        """Test NewDatabaseDBInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
