# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.backups_response import BackupsResponse

class TestBackupsResponse(unittest.TestCase):
    """BackupsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackupsResponse:
        """Test BackupsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackupsResponse`
        """
        model = BackupsResponse()
        if include_optional:
            return BackupsResponse(
                items = [
                    wodby.models.backup.Backup(
                        id = 56, 
                        name = '', 
                        status = '', 
                        app_instance_id = 56, 
                        app_service_id = 56, 
                        database_id = 56, 
                        database_db_id = 56, 
                        backup_preset_id = 56, 
                        manual = True, 
                        integration_id = 56, 
                        task_id = 56, 
                        size = 0, 
                        options = [
                            wodby.models.backup_option.BackupOption(
                                name = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 56,
                next_page = 56
            )
        else:
            return BackupsResponse(
                items = [
                    wodby.models.backup.Backup(
                        id = 56, 
                        name = '', 
                        status = '', 
                        app_instance_id = 56, 
                        app_service_id = 56, 
                        database_id = 56, 
                        database_db_id = 56, 
                        backup_preset_id = 56, 
                        manual = True, 
                        integration_id = 56, 
                        task_id = 56, 
                        size = 0, 
                        options = [
                            wodby.models.backup_option.BackupOption(
                                name = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 56,
        )
        """

    def testBackupsResponse(self):
        """Test BackupsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
