# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.app_builds_response import AppBuildsResponse

class TestAppBuildsResponse(unittest.TestCase):
    """AppBuildsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppBuildsResponse:
        """Test AppBuildsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppBuildsResponse`
        """
        model = AppBuildsResponse()
        if include_optional:
            return AppBuildsResponse(
                items = [
                    wodby.models.app_build.AppBuild(
                        id = 56, 
                        number = 56, 
                        status = '', 
                        app_instance_id = 56, 
                        app_service_id = 56, 
                        git_ref_type = '', 
                        git_ref = '', 
                        commit_hash = '', 
                        commit_message = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 56,
                next_page = 56
            )
        else:
            return AppBuildsResponse(
                items = [
                    wodby.models.app_build.AppBuild(
                        id = 56, 
                        number = 56, 
                        status = '', 
                        app_instance_id = 56, 
                        app_service_id = 56, 
                        git_ref_type = '', 
                        git_ref = '', 
                        commit_hash = '', 
                        commit_message = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 56,
        )
        """

    def testAppBuildsResponse(self):
        """Test AppBuildsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
