# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.git_repos_api import GitReposApi


class TestGitReposApi(unittest.TestCase):
    """GitReposApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GitReposApi()

    def tearDown(self) -> None:
        pass

    def test_get_git_repo_usages(self) -> None:
        """Test case for get_git_repo_usages

        Get Git repository usages
        """
        pass

    def test_update_git_repo_from_git(self) -> None:
        """Test case for update_git_repo_from_git

        Update all Git repository usages
        """
        pass


if __name__ == '__main__':
    unittest.main()
