# coding: utf-8

"""
    Wodby 2.0 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.app_service import AppService

class TestAppService(unittest.TestCase):
    """AppService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppService:
        """Test AppService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppService`
        """
        model = AppService()
        if include_optional:
            return AppService(
                id = 56,
                name = '',
                title = '',
                type = '',
                status = '',
                replicas = 56,
                version = '',
                main = True,
                disabled = True,
                external = True,
                required = True,
                needs_rebuild = True,
                needs_redeploy = True,
                configuration_ready = True,
                app_instance_id = 56,
                service_rev_id = 56,
                parent_app_service_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AppService(
                id = 56,
                name = '',
                title = '',
                type = '',
                status = '',
                replicas = 56,
                version = '',
                main = True,
                disabled = True,
                external = True,
                required = True,
                needs_rebuild = True,
                needs_redeploy = True,
                configuration_ready = True,
                app_instance_id = 56,
                service_rev_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAppService(self):
        """Test AppService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
