# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.backups_api import BackupsApi


class TestBackupsApi(unittest.TestCase):
    """BackupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackupsApi()

    def tearDown(self) -> None:
        pass

    def test_backups_get(self) -> None:
        """Test case for backups_get

        List backups
        """
        pass

    def test_backups_id_get(self) -> None:
        """Test case for backups_id_get

        Get backup
        """
        pass

    def test_backups_post(self) -> None:
        """Test case for backups_post

        Create backup
        """
        pass


if __name__ == '__main__':
    unittest.main()
