# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.volume_size_input import VolumeSizeInput

class TestVolumeSizeInput(unittest.TestCase):
    """VolumeSizeInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolumeSizeInput:
        """Test VolumeSizeInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolumeSizeInput`
        """
        model = VolumeSizeInput()
        if include_optional:
            return VolumeSizeInput(
                name = '',
                size = 56
            )
        else:
            return VolumeSizeInput(
                name = '',
                size = 56,
        )
        """

    def testVolumeSizeInput(self):
        """Test VolumeSizeInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
