# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.helm_chart_workload import HelmChartWorkload

class TestHelmChartWorkload(unittest.TestCase):
    """HelmChartWorkload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelmChartWorkload:
        """Test HelmChartWorkload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelmChartWorkload`
        """
        model = HelmChartWorkload()
        if include_optional:
            return HelmChartWorkload(
                kind = '',
                name = '',
                labels = {
                    'key' : ''
                    },
                selector = {
                    'key' : ''
                    },
                pod_labels = {
                    'key' : ''
                    },
                containers = [
                    wodby.models.helm_chart_container.HelmChartContainer(
                        name = '', 
                        image = '', 
                        command = [
                            ''
                            ], 
                        args = [
                            ''
                            ], 
                        ports = [
                            wodby.models.helm_chart_container_port.HelmChartContainerPort(
                                name = '', 
                                number = 56, 
                                protocol = '', )
                            ], 
                        env = [
                            ''
                            ], )
                    ],
                init_containers = [
                    wodby.models.helm_chart_container.HelmChartContainer(
                        name = '', 
                        image = '', 
                        command = [
                            ''
                            ], 
                        args = [
                            ''
                            ], 
                        ports = [
                            wodby.models.helm_chart_container_port.HelmChartContainerPort(
                                name = '', 
                                number = 56, 
                                protocol = '', )
                            ], 
                        env = [
                            ''
                            ], )
                    ],
                volumes = [
                    wodby.models.helm_chart_volume_claim.HelmChartVolumeClaim(
                        name = '', 
                        size = '', 
                        storage_class_name = '', 
                        access_modes = [
                            ''
                            ], )
                    ]
            )
        else:
            return HelmChartWorkload(
                kind = '',
                name = '',
        )
        """

    def testHelmChartWorkload(self):
        """Test HelmChartWorkload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
