# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.update_stack_from_git_request import UpdateStackFromGitRequest

class TestUpdateStackFromGitRequest(unittest.TestCase):
    """UpdateStackFromGitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateStackFromGitRequest:
        """Test UpdateStackFromGitRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateStackFromGitRequest`
        """
        model = UpdateStackFromGitRequest()
        if include_optional:
            return UpdateStackFromGitRequest(
                git_ref = '',
                git_ref_type = ''
            )
        else:
            return UpdateStackFromGitRequest(
                git_ref = '',
                git_ref_type = '',
        )
        """

    def testUpdateStackFromGitRequest(self):
        """Test UpdateStackFromGitRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
