# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.integrations_api import IntegrationsApi


class TestIntegrationsApi(unittest.TestCase):
    """IntegrationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntegrationsApi()

    def tearDown(self) -> None:
        pass

    def test_integrations_by_name_name_get(self) -> None:
        """Test case for integrations_by_name_name_get

        Get integration by name
        """
        pass

    def test_integrations_get(self) -> None:
        """Test case for integrations_get

        List integrations
        """
        pass

    def test_integrations_id_delete(self) -> None:
        """Test case for integrations_id_delete

        Delete integration
        """
        pass

    def test_integrations_id_put(self) -> None:
        """Test case for integrations_id_put

        Update integration
        """
        pass

    def test_integrations_post(self) -> None:
        """Test case for integrations_post

        Create integration
        """
        pass


if __name__ == '__main__':
    unittest.main()
