# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.new_managed_cluster_input import NewManagedClusterInput

class TestNewManagedClusterInput(unittest.TestCase):
    """NewManagedClusterInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewManagedClusterInput:
        """Test NewManagedClusterInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewManagedClusterInput`
        """
        model = NewManagedClusterInput()
        if include_optional:
            return NewManagedClusterInput(
                demo = True,
                single_node = True,
                region = '',
                machine_type = '',
                min_node_count = 56,
                max_node_count = 56
            )
        else:
            return NewManagedClusterInput(
                demo = True,
        )
        """

    def testNewManagedClusterInput(self):
        """Test NewManagedClusterInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
