# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.app_environments_api import AppEnvironmentsApi


class TestAppEnvironmentsApi(unittest.TestCase):
    """AppEnvironmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppEnvironmentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_app_environment(self) -> None:
        """Test case for create_app_environment

        Create app environment
        """
        pass

    def test_delete_app_environment(self) -> None:
        """Test case for delete_app_environment

        Delete app environment
        """
        pass

    def test_get_app_environment(self) -> None:
        """Test case for get_app_environment

        Get app environment
        """
        pass

    def test_get_app_environment_by_name(self) -> None:
        """Test case for get_app_environment_by_name

        Get app environment by name
        """
        pass

    def test_get_app_environment_cicd_settings(self) -> None:
        """Test case for get_app_environment_cicd_settings

        Get app environment CI/CD settings
        """
        pass

    def test_list_app_environments(self) -> None:
        """Test case for list_app_environments

        List app environments
        """
        pass

    def test_reconcile_app_environment_stack(self) -> None:
        """Test case for reconcile_app_environment_stack

        Reconcile app environment stack
        """
        pass

    def test_update_app_environment(self) -> None:
        """Test case for update_app_environment

        Update app environment
        """
        pass

    def test_update_app_environment_cicd_settings(self) -> None:
        """Test case for update_app_environment_cicd_settings

        Update app environment CI/CD settings
        """
        pass

    def test_update_app_environment_maintenance_mode(self) -> None:
        """Test case for update_app_environment_maintenance_mode

        Update app environment maintenance mode
        """
        pass

    def test_update_app_environment_settings(self) -> None:
        """Test case for update_app_environment_settings

        Update app environment settings
        """
        pass

    def test_upgrade_app_environment_stack(self) -> None:
        """Test case for upgrade_app_environment_stack

        Upgrade app environment stack
        """
        pass


if __name__ == '__main__':
    unittest.main()
