# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.app_routes_api import AppRoutesApi


class TestAppRoutesApi(unittest.TestCase):
    """AppRoutesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppRoutesApi()

    def tearDown(self) -> None:
        pass

    def test_app_routes_get(self) -> None:
        """Test case for app_routes_get

        List app routes
        """
        pass

    def test_app_routes_id_delete(self) -> None:
        """Test case for app_routes_id_delete

        Delete app route
        """
        pass

    def test_app_routes_id_get(self) -> None:
        """Test case for app_routes_id_get

        Get app route
        """
        pass

    def test_app_routes_id_put(self) -> None:
        """Test case for app_routes_id_put

        Update app route
        """
        pass

    def test_app_routes_post(self) -> None:
        """Test case for app_routes_post

        Create app route
        """
        pass


if __name__ == '__main__':
    unittest.main()
