# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.app_service_configuration_issue import AppServiceConfigurationIssue

class TestAppServiceConfigurationIssue(unittest.TestCase):
    """AppServiceConfigurationIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppServiceConfigurationIssue:
        """Test AppServiceConfigurationIssue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppServiceConfigurationIssue`
        """
        model = AppServiceConfigurationIssue()
        if include_optional:
            return AppServiceConfigurationIssue(
                app_service_id = 56,
                app_service_name = '',
                app_service_title = '',
                code = '',
                name = '',
                title = '',
                message = ''
            )
        else:
            return AppServiceConfigurationIssue(
                app_service_id = 56,
                app_service_name = '',
                app_service_title = '',
                code = '',
                name = '',
                title = '',
                message = '',
        )
        """

    def testAppServiceConfigurationIssue(self):
        """Test AppServiceConfigurationIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
