# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.api.app_deployments_api import AppDeploymentsApi


class TestAppDeploymentsApi(unittest.TestCase):
    """AppDeploymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppDeploymentsApi()

    def tearDown(self) -> None:
        pass

    def test_app_deployments_get(self) -> None:
        """Test case for app_deployments_get

        List app deployments
        """
        pass

    def test_app_deployments_id_get(self) -> None:
        """Test case for app_deployments_id_get

        Get deployment
        """
        pass

    def test_app_deployments_post(self) -> None:
        """Test case for app_deployments_post

        Create deployment
        """
        pass


if __name__ == '__main__':
    unittest.main()
