# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.stack_revision_link_issue import StackRevisionLinkIssue

class TestStackRevisionLinkIssue(unittest.TestCase):
    """StackRevisionLinkIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StackRevisionLinkIssue:
        """Test StackRevisionLinkIssue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StackRevisionLinkIssue`
        """
        model = StackRevisionLinkIssue()
        if include_optional:
            return StackRevisionLinkIssue(
                code = '',
                stack_service_id = 56,
                stack_service_name = '',
                stack_service_title = '',
                link_name = '',
                target_stack_service_id = 56,
                target_stack_service_name = '',
                target_stack_service_title = '',
                message = ''
            )
        else:
            return StackRevisionLinkIssue(
                code = '',
                stack_service_id = 56,
                stack_service_name = '',
                stack_service_title = '',
                message = '',
        )
        """

    def testStackRevisionLinkIssue(self):
        """Test StackRevisionLinkIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
