# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.new_backup_preset_input import NewBackupPresetInput

class TestNewBackupPresetInput(unittest.TestCase):
    """NewBackupPresetInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewBackupPresetInput:
        """Test NewBackupPresetInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewBackupPresetInput`
        """
        model = NewBackupPresetInput()
        if include_optional:
            return NewBackupPresetInput(
                app_instance_id = 56,
                app_service_id = 56,
                database_id = 56,
                database_db_id = 56,
                org_id = 56,
                env_id = 56,
                backup_name = '',
                integration_id = 56,
                bucket = '',
                storage_class = '',
                disabled = True,
                override = True,
                auto = True,
                crontab = '',
                duration = 30
            )
        else:
            return NewBackupPresetInput(
                integration_id = 56,
                bucket = '',
                disabled = True,
                override = True,
        )
        """

    def testNewBackupPresetInput(self):
        """Test NewBackupPresetInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
