# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wodby.models.service_manifest_env_var import ServiceManifestEnvVar

class TestServiceManifestEnvVar(unittest.TestCase):
    """ServiceManifestEnvVar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceManifestEnvVar:
        """Test ServiceManifestEnvVar
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceManifestEnvVar`
        """
        model = ServiceManifestEnvVar()
        if include_optional:
            return ServiceManifestEnvVar(
                name = '',
                value = '',
                secret = True,
                env = '',
                runtime = True,
                build = True
            )
        else:
            return ServiceManifestEnvVar(
                name = '',
                value = '',
                secret = True,
                runtime = True,
                build = True,
        )
        """

    def testServiceManifestEnvVar(self):
        """Test ServiceManifestEnvVar"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
