# coding: utf-8

# flake8: noqa
"""
    Wodby API Reference

    # Introduction  The Wodby API is organized around REST. Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, like HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients.  JSON is returned by all API responses, including errors.  # Authentication  Authenticate your account by including your secret key in API requests. You can manage your API keys in the Dashboard. Your API keys carry many privileges, so be sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as GitHub, client-side code, and so forth.  All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.  Example of authenticated request: ``` curl https://api.wodby.com/api/v3/user -H 'X-API-KEY: <MY API TOKEN>' ```   # noqa: E501

    OpenAPI spec version: 3.x
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from wodby_sdk.models.app import App
from wodby_sdk.models.backup import Backup
from wodby_sdk.models.domain import Domain
from wodby_sdk.models.git_repo import GitRepo
from wodby_sdk.models.instance import Instance
from wodby_sdk.models.instance_type import InstanceType
from wodby_sdk.models.org import Org
from wodby_sdk.models.request_app_create import RequestAppCreate
from wodby_sdk.models.request_app_create_git import RequestAppCreateGit
from wodby_sdk.models.request_app_create_services import RequestAppCreateServices
from wodby_sdk.models.request_instance_create import RequestInstanceCreate
from wodby_sdk.models.request_instance_create_git import RequestInstanceCreateGit
from wodby_sdk.models.request_instance_deploy import RequestInstanceDeploy
from wodby_sdk.models.request_instance_deploy_codebase import RequestInstanceDeployCodebase
from wodby_sdk.models.response_task import ResponseTask
from wodby_sdk.models.response_task_app import ResponseTaskApp
from wodby_sdk.models.response_task_instance import ResponseTaskInstance
from wodby_sdk.models.server import Server
from wodby_sdk.models.stack import Stack
from wodby_sdk.models.stack_service import StackService
from wodby_sdk.models.task import Task
from wodby_sdk.models.user import User
from wodby_sdk.models.uuid import Uuid
