# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AppServiceToken(BaseModel):
    """
    AppServiceToken
    """ # noqa: E501
    id: StrictInt
    app_service_id: StrictInt = Field(alias="appServiceId")
    name: StrictStr
    value: StrictStr
    value_secret_id: Optional[StrictInt] = Field(default=None, alias="valueSecretId")
    env_type: Optional[StrictStr] = Field(default=None, alias="envType")
    created_at: datetime = Field(alias="createdAt")
    __properties: ClassVar[List[str]] = ["id", "appServiceId", "name", "value", "valueSecretId", "envType", "createdAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppServiceToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if value_secret_id (nullable) is None
        # and model_fields_set contains the field
        if self.value_secret_id is None and "value_secret_id" in self.model_fields_set:
            _dict['valueSecretId'] = None

        # set to None if env_type (nullable) is None
        # and model_fields_set contains the field
        if self.env_type is None and "env_type" in self.model_fields_set:
            _dict['envType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppServiceToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "appServiceId": obj.get("appServiceId"),
            "name": obj.get("name"),
            "value": obj.get("value"),
            "valueSecretId": obj.get("valueSecretId"),
            "envType": obj.get("envType"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


