# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Backup(BaseModel):
    """
    Backup
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    status: StrictStr
    app_instance_id: Optional[StrictInt] = Field(default=None, alias="appInstanceId")
    app_service_id: Optional[StrictInt] = Field(default=None, alias="appServiceId")
    database_id: Optional[StrictInt] = Field(default=None, alias="databaseId")
    database_db_id: Optional[StrictInt] = Field(default=None, alias="databaseDbId")
    integration_id: Optional[StrictInt] = Field(description="Storage integration that owns the backup. Null identifies Wodby's built-in blob storage.", alias="integrationId")
    task_id: Optional[StrictInt] = Field(default=None, alias="taskId")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    started_at: Optional[datetime] = Field(default=None, alias="startedAt")
    ended_at: Optional[datetime] = Field(default=None, alias="endedAt")
    __properties: ClassVar[List[str]] = ["id", "name", "status", "appInstanceId", "appServiceId", "databaseId", "databaseDbId", "integrationId", "taskId", "createdAt", "updatedAt", "startedAt", "endedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Backup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if app_instance_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_instance_id is None and "app_instance_id" in self.model_fields_set:
            _dict['appInstanceId'] = None

        # set to None if app_service_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_service_id is None and "app_service_id" in self.model_fields_set:
            _dict['appServiceId'] = None

        # set to None if database_id (nullable) is None
        # and model_fields_set contains the field
        if self.database_id is None and "database_id" in self.model_fields_set:
            _dict['databaseId'] = None

        # set to None if database_db_id (nullable) is None
        # and model_fields_set contains the field
        if self.database_db_id is None and "database_db_id" in self.model_fields_set:
            _dict['databaseDbId'] = None

        # set to None if integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.integration_id is None and "integration_id" in self.model_fields_set:
            _dict['integrationId'] = None

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['taskId'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['startedAt'] = None

        # set to None if ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.ended_at is None and "ended_at" in self.model_fields_set:
            _dict['endedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Backup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "appInstanceId": obj.get("appInstanceId"),
            "appServiceId": obj.get("appServiceId"),
            "databaseId": obj.get("databaseId"),
            "databaseDbId": obj.get("databaseDbId"),
            "integrationId": obj.get("integrationId"),
            "taskId": obj.get("taskId"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "startedAt": obj.get("startedAt"),
            "endedAt": obj.get("endedAt")
        })
        return _obj


