# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wodby.models.cluster_capabilities import ClusterCapabilities
from wodby.models.cluster_settings import ClusterSettings
from wodby.models.storage_class import StorageClass
from typing import Optional, Set
from typing_extensions import Self

class Cluster(BaseModel):
    """
    Cluster
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    title: StrictStr
    status: StrictStr
    serverless: StrictBool
    demo: StrictBool
    wodby: StrictBool
    k3s: StrictBool
    single_node: StrictBool = Field(alias="singleNode")
    version: Optional[StrictStr] = None
    infra_version: StrictStr = Field(alias="infraVersion")
    min_node_count: Optional[StrictInt] = Field(default=None, alias="minNodeCount")
    max_node_count: Optional[StrictInt] = Field(default=None, alias="maxNodeCount")
    last_nodes_ready: Optional[StrictInt] = Field(default=None, alias="lastNodesReady")
    last_nodes_total: Optional[StrictInt] = Field(default=None, alias="lastNodesTotal")
    region: Optional[StrictStr] = None
    zone: Optional[StrictStr] = None
    ips: Optional[List[StrictStr]] = None
    hostname: Optional[StrictStr] = None
    integration_id: Optional[StrictInt] = Field(default=None, alias="integrationId")
    org_id: StrictInt = Field(alias="orgId")
    capabilities: ClusterCapabilities
    settings: Optional[ClusterSettings] = None
    storage_classes: Optional[List[StorageClass]] = Field(default=None, alias="storageClasses")
    storage_classes_observed_at: Optional[datetime] = Field(default=None, alias="storageClassesObservedAt")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "name", "title", "status", "serverless", "demo", "wodby", "k3s", "singleNode", "version", "infraVersion", "minNodeCount", "maxNodeCount", "lastNodesReady", "lastNodesTotal", "region", "zone", "ips", "hostname", "integrationId", "orgId", "capabilities", "settings", "storageClasses", "storageClassesObservedAt", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cluster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of capabilities
        if self.capabilities:
            _dict['capabilities'] = self.capabilities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in storage_classes (list)
        _items = []
        if self.storage_classes:
            for _item_storage_classes in self.storage_classes:
                if _item_storage_classes:
                    _items.append(_item_storage_classes.to_dict())
            _dict['storageClasses'] = _items
        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        # set to None if min_node_count (nullable) is None
        # and model_fields_set contains the field
        if self.min_node_count is None and "min_node_count" in self.model_fields_set:
            _dict['minNodeCount'] = None

        # set to None if max_node_count (nullable) is None
        # and model_fields_set contains the field
        if self.max_node_count is None and "max_node_count" in self.model_fields_set:
            _dict['maxNodeCount'] = None

        # set to None if last_nodes_ready (nullable) is None
        # and model_fields_set contains the field
        if self.last_nodes_ready is None and "last_nodes_ready" in self.model_fields_set:
            _dict['lastNodesReady'] = None

        # set to None if last_nodes_total (nullable) is None
        # and model_fields_set contains the field
        if self.last_nodes_total is None and "last_nodes_total" in self.model_fields_set:
            _dict['lastNodesTotal'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        # set to None if zone (nullable) is None
        # and model_fields_set contains the field
        if self.zone is None and "zone" in self.model_fields_set:
            _dict['zone'] = None

        # set to None if ips (nullable) is None
        # and model_fields_set contains the field
        if self.ips is None and "ips" in self.model_fields_set:
            _dict['ips'] = None

        # set to None if hostname (nullable) is None
        # and model_fields_set contains the field
        if self.hostname is None and "hostname" in self.model_fields_set:
            _dict['hostname'] = None

        # set to None if integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.integration_id is None and "integration_id" in self.model_fields_set:
            _dict['integrationId'] = None

        # set to None if storage_classes (nullable) is None
        # and model_fields_set contains the field
        if self.storage_classes is None and "storage_classes" in self.model_fields_set:
            _dict['storageClasses'] = None

        # set to None if storage_classes_observed_at (nullable) is None
        # and model_fields_set contains the field
        if self.storage_classes_observed_at is None and "storage_classes_observed_at" in self.model_fields_set:
            _dict['storageClassesObservedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cluster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "serverless": obj.get("serverless"),
            "demo": obj.get("demo"),
            "wodby": obj.get("wodby"),
            "k3s": obj.get("k3s"),
            "singleNode": obj.get("singleNode"),
            "version": obj.get("version"),
            "infraVersion": obj.get("infraVersion"),
            "minNodeCount": obj.get("minNodeCount"),
            "maxNodeCount": obj.get("maxNodeCount"),
            "lastNodesReady": obj.get("lastNodesReady"),
            "lastNodesTotal": obj.get("lastNodesTotal"),
            "region": obj.get("region"),
            "zone": obj.get("zone"),
            "ips": obj.get("ips"),
            "hostname": obj.get("hostname"),
            "integrationId": obj.get("integrationId"),
            "orgId": obj.get("orgId"),
            "capabilities": ClusterCapabilities.from_dict(obj["capabilities"]) if obj.get("capabilities") is not None else None,
            "settings": ClusterSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "storageClasses": [StorageClass.from_dict(_item) for _item in obj["storageClasses"]] if obj.get("storageClasses") is not None else None,
            "storageClassesObservedAt": obj.get("storageClassesObservedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


