# coding: utf-8

"""
    Wodby 2.0 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wodby.models.import_from_input import ImportFromInput
from typing import Optional, Set
from typing_extensions import Self

class ImportInput(BaseModel):
    """
    ImportInput
    """ # noqa: E501
    import_name: Optional[StrictStr] = Field(default=None, alias="importName")
    source: StrictStr
    url: Optional[StrictStr] = None
    backup_id: Optional[StrictInt] = Field(default=None, alias="backupID")
    var_from: Optional[ImportFromInput] = Field(default=None, alias="from")
    __properties: ClassVar[List[str]] = ["importName", "source", "url", "backupID", "from"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImportInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['from'] = self.var_from.to_dict()
        # set to None if import_name (nullable) is None
        # and model_fields_set contains the field
        if self.import_name is None and "import_name" in self.model_fields_set:
            _dict['importName'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if backup_id (nullable) is None
        # and model_fields_set contains the field
        if self.backup_id is None and "backup_id" in self.model_fields_set:
            _dict['backupID'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImportInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "importName": obj.get("importName"),
            "source": obj.get("source"),
            "url": obj.get("url"),
            "backupID": obj.get("backupID"),
            "from": ImportFromInput.from_dict(obj["from"]) if obj.get("from") is not None else None
        })
        return _obj


