# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from wodby.models.kubernetes_version_upgrade_target import KubernetesVersionUpgradeTarget
from typing import Optional, Set
from typing_extensions import Self

class KubernetesVersionUpgradePlan(BaseModel):
    """
    KubernetesVersionUpgradePlan
    """ # noqa: E501
    current_version: StrictStr = Field(alias="currentVersion")
    provider_version: StrictStr = Field(alias="providerVersion")
    provider: StrictStr
    supported: StrictBool
    targets: List[KubernetesVersionUpgradeTarget]
    blockers: List[StrictStr]
    warnings: List[StrictStr]
    observed_at: datetime = Field(alias="observedAt")
    __properties: ClassVar[List[str]] = ["currentVersion", "providerVersion", "provider", "supported", "targets", "blockers", "warnings", "observedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KubernetesVersionUpgradePlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in targets (list)
        _items = []
        if self.targets:
            for _item_targets in self.targets:
                if _item_targets:
                    _items.append(_item_targets.to_dict())
            _dict['targets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KubernetesVersionUpgradePlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currentVersion": obj.get("currentVersion"),
            "providerVersion": obj.get("providerVersion"),
            "provider": obj.get("provider"),
            "supported": obj.get("supported"),
            "targets": [KubernetesVersionUpgradeTarget.from_dict(_item) for _item in obj["targets"]] if obj.get("targets") is not None else None,
            "blockers": obj.get("blockers"),
            "warnings": obj.get("warnings"),
            "observedAt": obj.get("observedAt")
        })
        return _obj


