# coding: utf-8

"""
    Wodby Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NewBackupInput(BaseModel):
    """
    NewBackupInput
    """ # noqa: E501
    app_service_id: Optional[StrictInt] = Field(default=None, alias="appServiceID")
    database_dbid: Optional[StrictInt] = Field(default=None, alias="databaseDBID")
    backup_name: Optional[StrictStr] = Field(default=None, alias="backupName")
    integration_id: StrictInt = Field(alias="integrationID")
    bucket: StrictStr
    storage_class: Optional[StrictStr] = Field(default=None, alias="storageClass")
    __properties: ClassVar[List[str]] = ["appServiceID", "databaseDBID", "backupName", "integrationID", "bucket", "storageClass"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewBackupInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if app_service_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_service_id is None and "app_service_id" in self.model_fields_set:
            _dict['appServiceID'] = None

        # set to None if database_dbid (nullable) is None
        # and model_fields_set contains the field
        if self.database_dbid is None and "database_dbid" in self.model_fields_set:
            _dict['databaseDBID'] = None

        # set to None if backup_name (nullable) is None
        # and model_fields_set contains the field
        if self.backup_name is None and "backup_name" in self.model_fields_set:
            _dict['backupName'] = None

        # set to None if storage_class (nullable) is None
        # and model_fields_set contains the field
        if self.storage_class is None and "storage_class" in self.model_fields_set:
            _dict['storageClass'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewBackupInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appServiceID": obj.get("appServiceID"),
            "databaseDBID": obj.get("databaseDBID"),
            "backupName": obj.get("backupName"),
            "integrationID": obj.get("integrationID"),
            "bucket": obj.get("bucket"),
            "storageClass": obj.get("storageClass")
        })
        return _obj


