# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from wodby.models.app_environment_settings_input import AppEnvironmentSettingsInput
from wodby.models.new_app_environment_access_input import NewAppEnvironmentAccessInput
from wodby.models.new_app_service_input import NewAppServiceInput
from typing import Optional, Set
from typing_extensions import Self

class NewAppEnvironmentInput(BaseModel):
    """
    NewAppEnvironmentInput
    """ # noqa: E501
    app_id: StrictInt = Field(alias="appId")
    environment_name: StrictStr = Field(alias="environmentName")
    environment_title: Optional[StrictStr] = Field(default=None, description="Defaults to environmentName when omitted.", alias="environmentTitle")
    environment_type: StrictStr = Field(alias="environmentType")
    domain: Optional[StrictStr] = Field(default=None, description="Defaults to environmentName.appName.orgDomain when omitted.")
    stack_rev_id: StrictInt = Field(alias="stackRevId")
    services: Optional[List[NewAppServiceInput]] = Field(default=None, description="Defaults to the stack revision's service defaults when omitted.")
    cluster_id: Optional[StrictInt] = Field(default=None, alias="clusterId")
    ci_integration_id: Optional[StrictInt] = Field(default=None, alias="ciIntegrationId")
    registry_integration_id: Optional[StrictInt] = Field(default=None, alias="registryIntegrationId")
    defer_initial_deployment: Optional[StrictBool] = Field(default=False, alias="deferInitialDeployment")
    settings: Optional[AppEnvironmentSettingsInput] = None
    access: Optional[NewAppEnvironmentAccessInput] = None
    __properties: ClassVar[List[str]] = ["appId", "environmentName", "environmentTitle", "environmentType", "domain", "stackRevId", "services", "clusterId", "ciIntegrationId", "registryIntegrationId", "deferInitialDeployment", "settings", "access"]

    @field_validator('environment_type')
    def environment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['prod', 'test', 'staging', 'dev', 'feature']):
            raise ValueError("must be one of enum values ('prod', 'test', 'staging', 'dev', 'feature')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewAppEnvironmentInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in services (list)
        _items = []
        if self.services:
            for _item_services in self.services:
                if _item_services:
                    _items.append(_item_services.to_dict())
            _dict['services'] = _items
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of access
        if self.access:
            _dict['access'] = self.access.to_dict()
        # set to None if cluster_id (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_id is None and "cluster_id" in self.model_fields_set:
            _dict['clusterId'] = None

        # set to None if ci_integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.ci_integration_id is None and "ci_integration_id" in self.model_fields_set:
            _dict['ciIntegrationId'] = None

        # set to None if registry_integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.registry_integration_id is None and "registry_integration_id" in self.model_fields_set:
            _dict['registryIntegrationId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewAppEnvironmentInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appId": obj.get("appId"),
            "environmentName": obj.get("environmentName"),
            "environmentTitle": obj.get("environmentTitle"),
            "environmentType": obj.get("environmentType"),
            "domain": obj.get("domain"),
            "stackRevId": obj.get("stackRevId"),
            "services": [NewAppServiceInput.from_dict(_item) for _item in obj["services"]] if obj.get("services") is not None else None,
            "clusterId": obj.get("clusterId"),
            "ciIntegrationId": obj.get("ciIntegrationId"),
            "registryIntegrationId": obj.get("registryIntegrationId"),
            "deferInitialDeployment": obj.get("deferInitialDeployment") if obj.get("deferInitialDeployment") is not None else False,
            "settings": AppEnvironmentSettingsInput.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "access": NewAppEnvironmentAccessInput.from_dict(obj["access"]) if obj.get("access") is not None else None
        })
        return _obj


