# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServiceDeploymentInput(BaseModel):
    """
    ServiceDeploymentInput
    """ # noqa: E501
    name: StrictStr
    image: StrictStr
    unmanaged_image: Optional[StrictBool] = Field(default=None, description="Set by the CI build when the image was produced from a Dockerfile that does not derive from the service image.", alias="unmanagedImage")
    dockerfile_path: Optional[StrictStr] = Field(default=None, description="Repository path of an author-provided Dockerfile, reported by the CI build.", alias="dockerfilePath")
    dockerfile_hash: Optional[StrictStr] = Field(default=None, description="SHA-256 of the Dockerfile that produced the image, reported by the CI build.", alias="dockerfileHash")
    __properties: ClassVar[List[str]] = ["name", "image", "unmanagedImage", "dockerfilePath", "dockerfileHash"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceDeploymentInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if unmanaged_image (nullable) is None
        # and model_fields_set contains the field
        if self.unmanaged_image is None and "unmanaged_image" in self.model_fields_set:
            _dict['unmanagedImage'] = None

        # set to None if dockerfile_path (nullable) is None
        # and model_fields_set contains the field
        if self.dockerfile_path is None and "dockerfile_path" in self.model_fields_set:
            _dict['dockerfilePath'] = None

        # set to None if dockerfile_hash (nullable) is None
        # and model_fields_set contains the field
        if self.dockerfile_hash is None and "dockerfile_hash" in self.model_fields_set:
            _dict['dockerfileHash'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceDeploymentInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "image": obj.get("image"),
            "unmanagedImage": obj.get("unmanagedImage"),
            "dockerfilePath": obj.get("dockerfilePath"),
            "dockerfileHash": obj.get("dockerfileHash")
        })
        return _obj


