# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wodby.models.service_deployment_configuration import ServiceDeploymentConfiguration
from wodby.models.stack_service_container import StackServiceContainer
from wodby.models.stack_service_option import StackServiceOption
from wodby.models.stack_service_setting import StackServiceSetting
from typing import Optional, Set
from typing_extensions import Self

class StackService(BaseModel):
    """
    StackService
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    title: StrictStr
    type: StrictStr
    main: StrictBool
    disabled: StrictBool
    required: StrictBool
    replicas: StrictInt
    service_rev_pinned: StrictBool = Field(alias="serviceRevPinned")
    outdated: StrictBool
    service_rev_id: StrictInt = Field(alias="serviceRevId")
    service_rev_name: StrictStr = Field(alias="serviceRevName")
    service_rev_title: StrictStr = Field(alias="serviceRevTitle")
    service_rev_version: StrictStr = Field(alias="serviceRevVersion")
    build_source_integration_id: Optional[StrictInt] = Field(default=None, alias="buildSourceIntegrationId")
    build_source_remote_repo_id: Optional[StrictStr] = Field(default=None, alias="buildSourceRemoteRepoId")
    options: Optional[List[StackServiceOption]] = None
    settings: Optional[List[StackServiceSetting]] = None
    containers: Optional[List[StackServiceContainer]] = None
    deployment_configuration: ServiceDeploymentConfiguration = Field(alias="deploymentConfiguration")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "name", "title", "type", "main", "disabled", "required", "replicas", "serviceRevPinned", "outdated", "serviceRevId", "serviceRevName", "serviceRevTitle", "serviceRevVersion", "buildSourceIntegrationId", "buildSourceRemoteRepoId", "options", "settings", "containers", "deploymentConfiguration", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StackService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in settings (list)
        _items = []
        if self.settings:
            for _item_settings in self.settings:
                if _item_settings:
                    _items.append(_item_settings.to_dict())
            _dict['settings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in containers (list)
        _items = []
        if self.containers:
            for _item_containers in self.containers:
                if _item_containers:
                    _items.append(_item_containers.to_dict())
            _dict['containers'] = _items
        # override the default output from pydantic by calling `to_dict()` of deployment_configuration
        if self.deployment_configuration:
            _dict['deploymentConfiguration'] = self.deployment_configuration.to_dict()
        # set to None if build_source_integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.build_source_integration_id is None and "build_source_integration_id" in self.model_fields_set:
            _dict['buildSourceIntegrationId'] = None

        # set to None if build_source_remote_repo_id (nullable) is None
        # and model_fields_set contains the field
        if self.build_source_remote_repo_id is None and "build_source_remote_repo_id" in self.model_fields_set:
            _dict['buildSourceRemoteRepoId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StackService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "main": obj.get("main"),
            "disabled": obj.get("disabled"),
            "required": obj.get("required"),
            "replicas": obj.get("replicas"),
            "serviceRevPinned": obj.get("serviceRevPinned"),
            "outdated": obj.get("outdated"),
            "serviceRevId": obj.get("serviceRevId"),
            "serviceRevName": obj.get("serviceRevName"),
            "serviceRevTitle": obj.get("serviceRevTitle"),
            "serviceRevVersion": obj.get("serviceRevVersion"),
            "buildSourceIntegrationId": obj.get("buildSourceIntegrationId"),
            "buildSourceRemoteRepoId": obj.get("buildSourceRemoteRepoId"),
            "options": [StackServiceOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "settings": [StackServiceSetting.from_dict(_item) for _item in obj["settings"]] if obj.get("settings") is not None else None,
            "containers": [StackServiceContainer.from_dict(_item) for _item in obj["containers"]] if obj.get("containers") is not None else None,
            "deploymentConfiguration": ServiceDeploymentConfiguration.from_dict(obj["deploymentConfiguration"]) if obj.get("deploymentConfiguration") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


