# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wodby.models.task_job import TaskJob
from typing import Optional, Set
from typing_extensions import Self

class Task(BaseModel):
    """
    Task
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    title: StrictStr
    status: StrictStr
    progress: StrictInt
    silent: StrictBool
    system: StrictBool
    user_id: StrictInt = Field(alias="userId")
    org_id: Optional[StrictInt] = Field(default=None, alias="orgId")
    project_ids: Optional[List[StrictInt]] = Field(default=None, alias="projectIds")
    app_id: Optional[StrictInt] = Field(default=None, alias="appId")
    app_instance_id: Optional[StrictInt] = Field(default=None, alias="appInstanceId")
    cluster_id: Optional[StrictInt] = Field(default=None, alias="clusterId")
    integration_id: Optional[StrictInt] = Field(default=None, alias="integrationId")
    service_id: Optional[StrictInt] = Field(default=None, alias="serviceId")
    stack_id: Optional[StrictInt] = Field(default=None, alias="stackId")
    provider_id: Optional[StrictInt] = Field(default=None, alias="providerId")
    origin_task_id: Optional[StrictInt] = Field(default=None, alias="originTaskId")
    spawned_task_ids: Optional[List[StrictInt]] = Field(default=None, alias="spawnedTaskIds")
    repeated_task_id: Optional[StrictInt] = Field(default=None, alias="repeatedTaskId")
    jobs: List[TaskJob]
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    started_at: Optional[datetime] = Field(default=None, alias="startedAt")
    ended_at: Optional[datetime] = Field(default=None, alias="endedAt")
    __properties: ClassVar[List[str]] = ["id", "name", "title", "status", "progress", "silent", "system", "userId", "orgId", "projectIds", "appId", "appInstanceId", "clusterId", "integrationId", "serviceId", "stackId", "providerId", "originTaskId", "spawnedTaskIds", "repeatedTaskId", "jobs", "createdAt", "updatedAt", "startedAt", "endedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Task from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in jobs (list)
        _items = []
        if self.jobs:
            for _item_jobs in self.jobs:
                if _item_jobs:
                    _items.append(_item_jobs.to_dict())
            _dict['jobs'] = _items
        # set to None if org_id (nullable) is None
        # and model_fields_set contains the field
        if self.org_id is None and "org_id" in self.model_fields_set:
            _dict['orgId'] = None

        # set to None if app_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_id is None and "app_id" in self.model_fields_set:
            _dict['appId'] = None

        # set to None if app_instance_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_instance_id is None and "app_instance_id" in self.model_fields_set:
            _dict['appInstanceId'] = None

        # set to None if cluster_id (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_id is None and "cluster_id" in self.model_fields_set:
            _dict['clusterId'] = None

        # set to None if integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.integration_id is None and "integration_id" in self.model_fields_set:
            _dict['integrationId'] = None

        # set to None if service_id (nullable) is None
        # and model_fields_set contains the field
        if self.service_id is None and "service_id" in self.model_fields_set:
            _dict['serviceId'] = None

        # set to None if stack_id (nullable) is None
        # and model_fields_set contains the field
        if self.stack_id is None and "stack_id" in self.model_fields_set:
            _dict['stackId'] = None

        # set to None if provider_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_id is None and "provider_id" in self.model_fields_set:
            _dict['providerId'] = None

        # set to None if origin_task_id (nullable) is None
        # and model_fields_set contains the field
        if self.origin_task_id is None and "origin_task_id" in self.model_fields_set:
            _dict['originTaskId'] = None

        # set to None if repeated_task_id (nullable) is None
        # and model_fields_set contains the field
        if self.repeated_task_id is None and "repeated_task_id" in self.model_fields_set:
            _dict['repeatedTaskId'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['startedAt'] = None

        # set to None if ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.ended_at is None and "ended_at" in self.model_fields_set:
            _dict['endedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Task from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "progress": obj.get("progress"),
            "silent": obj.get("silent"),
            "system": obj.get("system"),
            "userId": obj.get("userId"),
            "orgId": obj.get("orgId"),
            "projectIds": obj.get("projectIds"),
            "appId": obj.get("appId"),
            "appInstanceId": obj.get("appInstanceId"),
            "clusterId": obj.get("clusterId"),
            "integrationId": obj.get("integrationId"),
            "serviceId": obj.get("serviceId"),
            "stackId": obj.get("stackId"),
            "providerId": obj.get("providerId"),
            "originTaskId": obj.get("originTaskId"),
            "spawnedTaskIds": obj.get("spawnedTaskIds"),
            "repeatedTaskId": obj.get("repeatedTaskId"),
            "jobs": [TaskJob.from_dict(_item) for _item in obj["jobs"]] if obj.get("jobs") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "startedAt": obj.get("startedAt"),
            "endedAt": obj.get("endedAt")
        })
        return _obj


