# coding: utf-8

"""
    Wodby 2 Public API

    Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, SecretStr, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateAppAuthInput(BaseModel):
    """
    UpdateAppAuthInput
    """ # noqa: E501
    app_service_ids: Optional[List[StrictInt]] = Field(default=None, description="App services to protect. Omit every scope field to preserve the current scope, or pass an empty list to protect the whole app environment.", alias="appServiceIds")
    app_service_id: Optional[StrictInt] = Field(default=None, description="Single-service scope. Ignored when appServiceIds is supplied.", alias="appServiceId")
    app_route_id: Optional[StrictInt] = Field(default=None, description="Moves the entry to route scope. The owning app service is derived from the route.", alias="appRouteId")
    login: StrictStr
    password: Optional[SecretStr] = Field(default=None, description="Replaces the existing secret when supplied; omit to keep the current password.")
    realm: StrictStr
    __properties: ClassVar[List[str]] = ["appServiceIds", "appServiceId", "appRouteId", "login", "password", "realm"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAppAuthInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if app_service_ids (nullable) is None
        # and model_fields_set contains the field
        if self.app_service_ids is None and "app_service_ids" in self.model_fields_set:
            _dict['appServiceIds'] = None

        # set to None if app_service_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_service_id is None and "app_service_id" in self.model_fields_set:
            _dict['appServiceId'] = None

        # set to None if app_route_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_route_id is None and "app_route_id" in self.model_fields_set:
            _dict['appRouteId'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAppAuthInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appServiceIds": obj.get("appServiceIds"),
            "appServiceId": obj.get("appServiceId"),
            "appRouteId": obj.get("appRouteId"),
            "login": obj.get("login"),
            "password": obj.get("password"),
            "realm": obj.get("realm")
        })
        return _obj


